title: Giacomo Marcolin
description: Giacomo Marcolin is a PhD candidate in Economics at Northwestern University. Research interests include labor economics, public economics, gender economics, and discrimination.
lang: en
url: "https://giacomomarcolin.github.io"
baseurl: ""

markdown: kramdown
permalink: pretty

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
