title: Giacomo Marcolin
description: I am a PhD student in Economics at Northwestern University. My research interests are in labor economics and public economics. In the 2026–27 academic year, I will be a NBER Gender in the Economy dissertation fellow.
lang: en
url: "https://giacomomarcolin.github.io"
baseurl: ""

markdown: kramdown
permalink: pretty

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

plugins:
  - jekyll-sitemap
